---
title: "Afternoon Comp"
author: "Paloma Cartwright"
date: "19/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
library(lubridate)
library(kableExtra)
library(janitor)
```

## Wrangling 

### Check for duplicates 

```{r}
starwars_dupes <- get_dupes(starwars)

starwars_dupes_names <- starwars %>% 
  get_dupes(name)


starwars_dupes_eyes <- starwars %>% 
  get_dupes(eye_color)
```

### dplyr::across()

```{r}

sw_across <- starwars %>% 
  group_by(homeworld) %>% 
  summarise(across(where(is.numeric), mean, na.rm = TRUE))

```

```{r}
starwars %>% 
  filter(homeworld == "Naboo")
```

```{r}
starwars %>% 
  separate(skin_color, 
           into = c("col_1", "col_2"), 
           sep = ",")
```


```{r}
ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_point()
```


```{r}
troubleshooting <- penguins %>% 
  mutate(across(where(is.numeric), as.character)) %>% 
  mutate(island = fct_relevel(island, c("Dream", "Biscoe", "Torgersen"))) %>% 
  unite(island_yr, c(island, year), sep = "_") %>% 
  filter(species %in% c("Adelie", "Chinstrap")) %>% 
  relocate(island_yr, .after = "species") %>% 
  rename(penguin_spp = species)
```

```{r}
library(tidyverse)

df <- tribble(
  ~name, ~height, ~hair_color, 
  "Teddy", 2.2, "brown", 
  "Khora", 3.1, "white", 
  "Waffle", 1.0, "tan"
)

df %>% 
  filter(name == "Waffle")

```



